package me.jakob.songreporter.reporting.enums;

public enum Reason {
    INVALID_CREDENTIALS,
    SONG_NOT_LICENSED,
    NO_CCLI_SONGNUMBER,
    SITE_CODE_CHANGED,
    LOGIN_TIMEOUT,
    FAILED_REQUEST,
    NO_RESPONSE_BODY,
    ERRORCODE,
    NO_REQUEST_VERIFICATION_TOKEN
}
